const gameData = {
    categories: {
        house: {
            id: 'house',
            name: { en: "The House", ar: "البيت" },
            hint: { en: "Something found in a house", ar: "شيء موجود في البيت" },
            words: [
                { en: "Television", ar: "تلفزيون" },
                { en: "Sofa", ar: "كنبة" },
                { en: "Refrigerator", ar: "ثلاجة" },
                { en: "Bed", ar: "سرير" },
                { en: "Dining Table", ar: "طاولة طعام" },
                { en: "Microwave", ar: "ميكروويف" },
                { en: "Carpet", ar: "سجادة" },
                { en: "Wardrobe", ar: "خزانة ملابس" },
                { en: "Washing Machine", ar: "غسالة" },
                { en: "Air Conditioner", ar: "تكييف" },
                { en: "Mirror", ar: "مرآة" },
                { en: "Oven", ar: "فرن" },
                { en: "Lamp", ar: "لمبة" },
                { en: "Door", ar: "باب" }
            ]
        },
        diwaniya: {
            id: 'diwaniya',
            name: { en: "The Diwaniya", ar: "الدوانية" },
            hint: { en: "Something related to the Diwaniya", ar: "شيء مرتبط بالدوانية" },
            words: [
                { en: "Tea", ar: "شاي" },
                { en: "Coffee", ar: "قهوة" },
                { en: "Incense", ar: "بخور" },
                { en: "Playing Cards", ar: "ورق لعب" },
                { en: "Dates", ar: "تمر" },
                { en: "Dallah (Coffee Pot)", ar: "دلة" },
                { en: "Cushions", ar: "مساند" },
                { en: "Television", ar: "تلفزيون" },
                { en: "Snacks", ar: "مكسرات" },
                { en: "Incense Burner", ar: "مبخر" },
                { en: "Matches", ar: "كبريت" },
                { en: "Slippers", ar: "نعال" },
                { en: "Tea Pot", ar: "غوري" }
            ]
        },
        club: {
            id: 'club',
            name: { en: "The Club", ar: "النادي" },
            hint: { en: "Something found in a gym/club", ar: "شيء موجود في النادي" },
            words: [
                { en: "Dumbbells", ar: "أثقال" },
                { en: "Treadmill", ar: "جهاز مشي" },
                { en: "Protein Shake", ar: "بروتين شيك" },
                { en: "Towel", ar: "فوطة" },
                { en: "Water Bottle", ar: "مطارة ماء" },
                { en: "Boxing Gloves", ar: "قفازات ملاكمة" },
                { en: "Yoga Mat", ar: "سجادة يوغا" },
                { en: "Trainer", ar: "مدرب" },
                { en: "Lockers", ar: "خزائن" },
                { en: "Jump Rope", ar: "حبل قفز" },
                { en: "Sauna", ar: "ساونا" },
                { en: "Scale", ar: "ميزان" }
            ]
        },
        supermarket: {
            id: 'supermarket',
            name: { en: "Supermarket", ar: "الجمعية" },
            hint: { en: "Something bought at the supermarket", ar: "شيء تشتريه من الجمعية" },
            words: [
                { en: "Milk", ar: "حليب" },
                { en: "Bread", ar: "خبز" },
                { en: "Eggs", ar: "بيض" },
                { en: "Cheese", ar: "جبن" },
                { en: "Shopping Cart", ar: "عربة تسوق" },
                { en: "Cashier", ar: "كاشير" },
                { en: "Rice", ar: "عيش (أرز)" },
                { en: "Chips", ar: "بطاط شبس" },
                { en: "Vegetables", ar: "خضار" },
                { en: "Fruits", ar: "فواكه" },
                { en: "Detergent", ar: "صابون غسيل" },
                { en: "Juice", ar: "عصير" }
            ]
        },
        beach: {
            id: 'beach',
            name: { en: "The Beach", ar: "البحر" },
            hint: { en: "Something found at the beach", ar: "شيء موجود بالبحر" },
            words: [
                { en: "Sand", ar: "رمل" },
                { en: "Shells", ar: "قواقع" },
                { en: "Umbrella", ar: "مظلة" },
                { en: "Sunscreen", ar: "كريم شمس" },
                { en: "Towels", ar: "فوط" },
                { en: "Waves", ar: "أمواج" },
                { en: "Sunglasses", ar: "نظارة شمسية" },
                { en: "Boat", ar: "قارب (طراد)" },
                { en: "Fishing Rod", ar: "سنارة" },
                { en: "Life Jacket", ar: "سترة نجاة" },
                { en: "Swimsuit", ar: "مايوه" },
                { en: "Cooler", ar: "ثلاجة رحلات (مطارة)" }
            ]
        },
        school: {
            id: 'school',
            name: { en: "School", ar: "المدرسة" },
            hint: { en: "Something related to school", ar: "شيء متعلق بالمدرسة" },
            words: [
                { en: "Backpack", ar: "جنطة مدرسة" },
                { en: "Pencil", ar: "قلم رصاص" },
                { en: "Notebook", ar: "دفتر" },
                { en: "Teacher", ar: "مدرس" },
                { en: "Whiteboard", ar: "سبورة" },
                { en: "Desk", ar: "درج" },
                { en: "Exams", ar: "امتحانات" },
                { en: "Break / Recess", ar: "فرصة" },
                { en: "Calculator", ar: "آلة حاسبة" },
                { en: "Books", ar: "كتب" },
                { en: "Uniform", ar: "لبس مدرسة" },
                { en: "Eraser", ar: "مساحة" }
            ]
        },
        mall: {
            id: 'mall',
            name: { en: "The Mall", ar: "المجمع" },
            hint: { en: "Something found in a mall", ar: "شيء موجود في المجمع" },
            words: [
                { en: "Escalator", ar: "سلم كهربائي" },
                { en: "Boutique", ar: "محل ملابس" },
                { en: "Food Court", ar: "مطاعم" },
                { en: "Cinema", ar: "سينما" },
                { en: "Perfume Shop", ar: "محل عطور" },
                { en: "Security Guard", ar: "سكيورتي" },
                { en: "Elevator", ar: "مصعد" },
                { en: "Parking", ar: "مواقف" },
                { en: "Cafe", ar: "كافيه" },
                { en: "Fitting Room", ar: "غرفة قياس" },
                { en: "Bags", ar: "أكياس تسوق" },
                { en: "Sale / Discount", ar: "تنزيلات" }
            ]
        }
    }
};

const translations = {
    en: {
        app_title: "Who's<br>Out?",
        app_subtitle: "The Social Deduction Game",
        play: "Play",
        settings: "Settings",
        language: "Language",
        theme: "Theme",
        light: "Light",
        dark: "Dark",
        setup_title: "Game Setup",
        num_players: "Number of Players",
        category: "Category",
        start_game: "Start Game",
        pass_to: "Pass to",
        player: "Player",
        reveal: "Reveal",
        you_are_in: "You are IN",
        you_are_out: "You are OUT!",
        word_is: "The word is:",
        hint_is: "Hint:",
        word_was: "The word was:",
        next_player: "Next Player",
        questioning_phase: "Questioning Phase",
        asks: "asks",
        next_question: "Next Random Pair",
        start_voting: "Start Voting",
        voting_phase: "Voting Phase",
        vote_out: "Vote who is OUT",
        confirm_vote: "Confirm Vote",
        results: "Results",
        out_was: "The 'OUT' player was:",
        play_again: "Play Again",
        home: "Home",
        correct_guess: "You got it! The out player was caught.",
        wrong_guess: "Wrong guess! The out player wins.",
        create_room: "Create Room",
        join_room: "Join Room",
        play_local: "Play on one device",
        your_name: "Your Name",
        create: "Create",
        room_code: "Room Code",
        join: "Join",
        lobby: "Lobby",
        room_code_is: "Room Code:",
        players: "Players",
        leave_room: "Leave Room",
        role_assigned: "Your role is ready!",
        start_questioning: "Start Questioning Phase",
        waiting_for_host: "Waiting for host...",
        end_voting_show_results: "End Voting & Show Results",
        voted_for: "Voted for"
    },
    ar: {
        app_title: "منو<br>برا السالفة؟",
        app_subtitle: "لعبة الاستنتاج الاجتماعي",
        play: "العب",
        settings: "الإعدادات",
        language: "اللغة",
        theme: "المظهر",
        light: "فاتح",
        dark: "داكن",
        setup_title: "إعداد اللعبة",
        num_players: "عدد اللاعبين",
        category: "الفئة",
        start_game: "ابدأ اللعبة",
        pass_to: "مرر الجهاز إلى",
        player: "لاعب",
        reveal: "أظهر",
        you_are_in: "أنت بالسالفة",
        you_are_out: "أنت برا السالفة!",
        word_is: "الكلمة هي:",
        hint_is: "تلميح:",
        word_was: "الكلمة كانت:",
        next_player: "اللاعب التالي",
        questioning_phase: "فترة الأسئلة",
        asks: "يسأل",
        next_question: "اختيار عشوائي",
        start_voting: "ابدأ التصويت",
        voting_phase: "فترة التصويت",
        vote_out: "صوّت لمين برا السالفة",
        confirm_vote: "تأكيد التصويت",
        results: "النتائج",
        out_was: "اللاعب برا السالفة كان:",
        play_again: "العب مرة أخرى",
        home: "الرئيسية",
        correct_guess: "صحيح! تم صيد اللي برا السالفة.",
        wrong_guess: "غلط! فاز اللي برا السالفة.",
        create_room: "إنشاء غرفة (أونلاين)",
        join_room: "انضمام لغرفة (أونلاين)",
        play_local: "لعب على نفس الجهاز",
        your_name: "اسمك",
        create: "إنشاء",
        room_code: "رمز الغرفة",
        join: "انضمام",
        lobby: "الانتظار",
        room_code_is: "رمز الغرفة:",
        players: "اللاعبين",
        leave_room: "مغادرة الغرفة",
        role_assigned: "دورك جاهز!",
        start_questioning: "بدء فترة الأسئلة",
        waiting_for_host: "بانتظار الهوست...",
        end_voting_show_results: "إنهاء التصويت وعرض النتائج",
        voted_for: "صوت لـ"
    }
};
